services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "15672:15672"
    networks:
      - rabbitmq-network

  general-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    image: scraping-general:dev
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./app:/app
    env_file:
      - .env
    networks:
      - rabbitmq-network
      - postgres-network

  postgres:
    image: postgres:17-bullseye
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - postgres-network
    command:
      postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all

volumes:
  local_postgres_data:

networks:
  rabbitmq-network:
    driver: bridge
  postgres-network:
    driver: bridge